PROG=	fin
SRCS=	\
	finance.c \
	grammar.y \
	token.l

CFLAGS = -Wall -g

NO_MAN = yes
CLEANFILES = gpdata finplan.sh
DISTCLEAN = cscope.*

cscope:
	find . -name "*.[chyl]" > cscope.files
	cscope -buq -F cscope.files

distclean:
	rm -f $(CLEANFILES) $(DISTCLEAN)

.include <bsd.prog.mk>
